apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: food-operations
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_HOST: "rds-postgres.food-operations.svc.cluster.local"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "elasticache-redis.food-operations.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "msk-kafka.food-operations.svc.cluster.local:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"
  LOG_LEVEL: "INFO"
