apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployments/api-gateway.yaml
  - deployments/core-services.yaml
  - deployments/polyglot-services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: enterprise-food-platform
