apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: food-operations
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change_me_in_cloud_secrets_manager"
  JWT_SECRET: "c2VjdXJlX2Zvb2Rfb3BlcmF0aW9uc19wbGF0Zm9ybV9qd3Rfc2VjcmV0X2tleV9mb3JfZGV2X2Vudmlyb25tZW50XzEyMzQ1Ng=="
